# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "CGO_ENABLED=0 go build -mod=vendor -gcflags='all=-N -l' -v -o ./tmp/app/src/main /usr/src/app/src/main.go"
# Binary file yields from `cmd`.
bin = "./tmp/app/src/main"

# Customize binary.
# This is how you start to run your application.
full_bin = "./tmp/app/src/main"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "yaml", "toml"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "test", "vendor"]
# Exclude specific regular expressions.
exclude_regex = ["(.*)_test.go"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 2000 # ms

[log]
# Show log time
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = false
