repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
  # - repo: https://github.com/tekwizely/pre-commit-golang
  #   rev: v0.8.3
  #   hooks:
  #     - id: my-cmd-repo
  #     - name: go-functional-tests
  - repo: local
    hooks:
      - id: go-functional-tests
        name: Functional tests
        description: Runs functional tests
        entry: make test
        language: golang
