# PRE-COMMIT HOOKS
# https://pre-commit.com/
# - brew install pre-commit
# - pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt

  - repo: local
    hooks:
      - id: go-functional-tests
        name: go-functional-tests
        description: Functional tests
        entry: make test
        language: golang
