# PRE-COMMIT HOOKS
# https://pre-commit.com/
# - brew install pre-commit
# - pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: my-cmd-repo
        name: go-functional-tests
        alias: go-functional-tests
        args: [make, test]

  # - repo: local
  #   hooks:
  #     - id: go-functional-tests-setup
  #       name: go-functional-tests-setup
  #       description: Functional tests setup
  #       entry: make test-setup
  #       language: golang
  #     - id: go-functional-tests
  #       name: go-functional-tests
  #       description: Functional tests
  #       entry: make test-only
  #       language: golang
  #     - id: go-functional-tests-teardown
  #       name: go-functional-tests-teardown
  #       description: Functional tests teardown
  #       entry: make test-teardown
  #       language: golang
