# This compose file will be automatically used by `docker compose up` (for dev)
version: "3.9"

services:

  # Running app with air for live-reload
  app:
    image: cosmtrek/air
    working_dir: /usr/src/app
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/src/app

  db:
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev123
    volumes:
      - mysql-db:/var/lib/mysql

  # Web-based DB UI
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql-db:
