FROM golang:1.19-alpine

WORKDIR /usr/src/app

EXPOSE 9000

# Add to alpine:
# - curl
RUN apk --no-cache add --update curl

# Pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Using Air https://github.com/cosmtrek/air to run Gin app for live-reload
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

CMD ["air"]
