# This compose file will be automatically used by `docker compose up` (for dev)
version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/src/app # volume used by Air for Gin live-reload
    depends_on:
      - mysql

  mysql:
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_USER: ppp.user
      MYSQL_PASSWORD: ppp123
      MYSQL_DATABASE: ppp
    volumes:
      - mysql-data:/var/lib/mysql

  # Web-based DB UI
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql-data:
